### ISSUE TITLE
Unable to download docker?

### ISSUE THREAD

**Issue by bobthebadguy** [cheeseandcereal/transmission_influxdb_exporter#1]
Hi,
When attempting to use `sudo docker run cheeseandcereal/transmission_influxdb_exporter:latest` as the instructions say, docker reports that access is denied. 
`docker: Error response from daemon: pull access denied for cheeseandcereal/transmission_influxdb_exporter, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.`
I'm no docker expert but I can't find anything I'm doing wrong. Thanks!

**Comment by cheeseandcereal** [comment]
Apparently I didn't have the container pushed to dockerhub. Should be there now, so you can try again.

**Comment by bobthebadguy** [comment]
Thanks, that fixed it!
