### ISSUE TITLE
Issues with Setup

### ISSUE THREAD

**Issue by ItsRainingHP** [cheeseandcereal/transmission_influxdb_exporter#3]
Hello @cheeseandcereal. I apologize to bother you but I have still been unsuccessful getting your dashboard running. I seem to be able to get your exporter running without issues in docker.

Here is my output for your docker:

`INFO:main:Transmission client transmission 15 points found for recording
INFO:main:Writing 15 data points to influxdb
INFO:main:Transmission client transmission 15 points found for recording
INFO:main:Writing 15 data points to influxdb
INFO:main:Transmission client transmission 15 points found for recording
INFO:main:Writing 15 data points to influxdb`

However I am still unsuccessful at getting grafana to connect to InfluxDB with Flux. I refer you to my other post that shows many of my settings. If you have any direction that would be helpful. I suspect many of your potential users get stuck where I am and fail to utilize this amazing docker you have created.

> Still fails for me
> 
> ![image](https://user-images.githubusercontent.com/79205731/126887130-077151e0-87ef-458d-bfa1-47e2884da034.png)
> 
> My config for this container is the same as original post.
> 
> Output Log for transmission_influxdb_exporter container:
> 
> ```
> INFO:main:Transmission client transmission-sonarr 7 points found for recording
> INFO:main:Writing 7 data points to influxdb
> INFO:main:Transmission client transmission-sonarr 7 points found for recording
> INFO:main:Writing 7 data points to influxdb
> INFO:main:Transmission client transmission-sonarr 7 points found for recording
> INFO:main:Writing 7 data points to influxdb
> ```
> 
> Here is the last few lines of my influxdb:
> 
> ```
> [httpd] 172.17.0.1 - root [24/Jul/2021:20:51:05 -0700] "POST /query?db=transmission&q=DROP+MEASUREMENT+%22tracker_storage%22 HTTP/1.1 " 200 58 "-" "python-requests/2.25.1" 8983513e-ecfb-11eb-b4e4-0242ac11000a 995060
> [httpd] 172.17.0.1 - root [24/Jul/2021:20:51:06 -0700] "POST /write?db=transmission HTTP/1.1 " 204 0 "-" "python-requests/2.25.1" 8a1bb6bb-ecfb-11eb-b4e5-0242ac11000a 62098
> [httpd] 172.17.0.1 - root [24/Jul/2021:20:51:06 -0700] "POST /write?db=transmission HTTP/1.1 " 204 0 "-" "python-requests/2.25.1" 8a26fc8c-ecfb-11eb-b4e6-0242ac11000a 33657
> [httpd] 172.17.0.1 - root [24/Jul/2021:20:52:06 -0700] "POST /query?db=transmission&q=DROP+MEASUREMENT+%22tracker_storage%22 HTTP/1.1 " 200 58 "-" "python-requests/2.25.1" adfef05e-ecfb-11eb-b4ea-0242ac11000a 1400363
> [httpd] 172.17.0.1 - root [24/Jul/2021:20:52:07 -0700] "POST /write?db=transmission HTTP/1.1 " 204 0 "-" "python-requests/2.25.1" aed52dab-ecfb-11eb-b4eb-0242ac11000a 235992
> [httpd] 172.17.0.1 - root [24/Jul/2021:20:52:08 -0700] "POST /write?db=transmission HTTP/1.1 " 204 0 "-" "python-requests/2.25.1" aefa569b-ecfb-11eb-b4ec-0242ac11000a 66662
> [httpd] 172.17.0.1 - root [24/Jul/2021:20:53:08 -0700] "POST /query?db=transmission&q=DROP+MEASUREMENT+%22tracker_storage%22 HTTP/1.1 " 200 58 "-" "python-requests/2.25.1" d2d6d889-ecfb-11eb-b4ef-0242ac11000a 661810
> [httpd] 172.17.0.1 - root [24/Jul/2021:20:53:08 -0700] "POST /write?db=transmission HTTP/1.1 " 204 0 "-" "python-requests/2.25.1" d33c90ac-ecfb-11eb-b4f0-0242ac11000a 107508
> [httpd] 172.17.0.1 - root [24/Jul/2021:20:53:09 -0700] "POST /write?db=transmission HTTP/1.1 " 204 0 "-" "python-requests/2.25.1" d34e6524-ecfb-11eb-b4f1-0242ac11000a 25254
> [httpd] 172.17.0.1 - root [24/Jul/2021:20:54:09 -0700] "POST /query?db=transmission&q=DROP+MEASUREMENT+%22tracker_storage%22 HTTP/1.1 " 200 58 "-" "python-requests/2.25.1" f725715e-ecfb-11eb-b4f4-0242ac11000a 2263818
> [httpd] 172.17.0.1 - root [24/Jul/2021:20:54:11 -0700] "POST /write?db=transmission HTTP/1.1 " 204 0 "-" "python-requests/2.25.1" f87f6090-ecfb-11eb-b4f5-0242ac11000a 106469
> [httpd] 172.17.0.1 - root [24/Jul/2021:20:54:11 -0700] "POST /write?db=transmission HTTP/1.1 " 204 0 "-" "python-requests/2.25.1" f890b73a-ecfb-11eb-b4f6-0242ac11000a 21506
> [httpd] 172.17.0.1 - root [24/Jul/2021:20:55:11 -0700] "POST /query?db=transmission&q=DROP+MEASUREMENT+%22tracker_storage%22 HTTP/1.1 " 200 58 "-" "python-requests/2.25.1" 1c65eb76-ecfc-11eb-b4ff-0242ac11000a 1614276
> [httpd] 172.17.0.1 - root [24/Jul/2021:20:55:13 -0700] "POST /write?db=transmission HTTP/1.1 " 204 0 "-" "python-requests/2.25.1" 1d5d0480-ecfc-11eb-b500-0242ac11000a 93833
> [httpd] 172.17.0.1 - root [24/Jul/2021:20:55:13 -0700] "POST /write?db=transmission HTTP/1.1 " 204 0 "-" "python-requests/2.25.1" 1d6ccb6b-ecfc-11eb-b501-0242ac11000a 24446
> ```
> 
> Here is the InfluxDB Config.yml:
> 
> ```
> [http]
>   enabled = true
>   flux-enabled=true
>   bind-address = "192.168.0.216:8086"
>   auth-enabled = false # Set to true
>   log-enabled = true
>   write-tracing = false
>   pprof-enabled = false
>   pprof-auth-enabled = false
>   debug-pprof-enabled = false
>   ping-auth-enabled = false
>   https-enabled = false
>   https-certificate = "/etc/ssl/influxdb.pem"
> ```

**Comment by cheeseandcereal** [comment]
I'm not sure what to tell you. The exporter program is working fine. You're having an issue configuring influxdb with grafana which doesn't really have anything to do with this repo aside from the fact that an example grafana dashboard is provided here.

I would recommend you check out the grafana docs: https://grafana.com/docs/grafana/latest/datasources/influxdb/influxdb-flux/
And if you're still having an issue with setting up grafana, open in issue with details in the grafana repo: https://github.com/grafana/grafana/issues

**Comment by cheeseandcereal** [comment]
This is my configuration if it would help:
![image](https://user-images.githubusercontent.com/11189778/148617012-cd0a6b9a-d792-40a0-88cc-e0c8fbdfd75b.png)

As for my influxdb configuration, these are the only changes I've made from the defaults:
```diff
--- influxdb.conf.dpkg-dist	2021-04-19 21:54:55.000000000 +0000
+++ influxdb.conf	2021-10-14 03:10:02.726910238 +0000
@@ -9,7 +9,7 @@
 # The data includes a random ID, os, arch, version, the number of series and other
 # usage data. No data from user databases is ever transmitted.
 # Change this option to true to disable reporting.
-# reporting-disabled = false
+reporting-disabled = true

 # Bind address to use for the RPC service for backup and restore.
 # bind-address = "127.0.0.1:8088"
@@ -140,7 +140,7 @@
   # and provide higher write throughput.
   # Valid size suffixes are k, m, or g (case insensitive, 1024 = 1k).
   # Values without a size suffix are in bytes.
-  # max-index-log-file-size = "1m"
+  max-index-log-file-size = "100m"

   # The size of the internal cache used in the TSI index to store previously
   # calculated series results. Cached results will be returned quickly from the cache rather
@@ -160,7 +160,7 @@

 [coordinator]
   # The default time a write request will wait until a "timeout" error is returned to the caller.
-  # write-timeout = "10s"
+  write-timeout = "30s"

   # The maximum number of concurrent queries allowed to be executing at one time.  If a query is
   # executed and exceeds this limit, an error is returned to the caller.  This limit can be disabled
@@ -251,7 +251,7 @@
   # enabled = true

   # Determines whether the Flux query endpoint is enabled.
-  # flux-enabled = false
+  flux-enabled = true

   # Determines whether the Flux query logging is enabled.
   # flux-log-enabled = false
@@ -331,7 +331,7 @@
   # bind-socket = "/var/run/influxdb.sock"

   # The maximum size of a client request body, in bytes. Setting this value to 0 disables the limit.
-  # max-body-size = 25000000
+  max-body-size = 0

   # The maximum number of writes processed concurrently.
   # Setting this to 0 disables the limit.
```

**Comment by ItsRainingHP** [comment]
I am still having issues. The docker works and is supposedly reporting. When I have more time I will open the DB and run queries. I have databases setup just fine but this one will not take. What are your auth credentials and token? Root and root are default I believe. Which then for the Token is root:root.

I entered exactly like yours the only thing I can see different would maybe be your config.json for this docker  or the things we cannot see like the token.

**Comment by cheeseandcereal** [comment]
auth isn't configured on my influxdb instance. I think i just put empty strings anywhere it asked for any auth info and it worked. I'm not really sure why else your influxdb instance would fail to connect with grafana. I don't really have any more info. You can check the info here and see if any of it is relevant, but I'm no expert in connecting influx to grafana: https://github.com/influxdata/influxdb-client-go/#influxdb-18-api-compatibility

**Comment by ItsRainingHP** [comment]
For those reading. I have finally figured out what was wrong with the file. I may create a tutorial video for this docker in the future. Merely setting the variable in the [HTTP] section of the config was the first step. You must set INFLUXDB_HTTP_FLUX_ENABLED=true as an environment variable.
