### ISSUE TITLE
List index out of range.

### ISSUE THREAD

**Issue by KoalaV2** [cheeseandcereal/transmission_influxdb_exporter#4]
```
INFO:transmission:Connecting` to transmission daemon transmission at 192.168.68.131:9091
INFO:influxdb:Connecting to influxdb
ERROR:main:Error collecting data points from transmission client transmission
list index out of range
INFO:main:Writing 0 data points to influxdb
```

Whenever trying to get data from transmission using either docker or locally it fails due to list index out of range, i've shortened it to the match case on line 121 in the transmission.py file.

**Comment by cheeseandcereal** [comment]
Interesting. Do you have torrents in transmission with no trackers? I suppose that could cause this issue. Either way I pushed [an update](https://github.com/cheeseandcereal/transmission_influxdb_exporter/commit/a445c2c70edcbfa20a19040bc5d7d7e17122b2d6) to try to mitigate this. Try using the latest code and/or docker container and let me know if you're still having the issue.

**Comment by KoalaV2** [comment]
Yep seems like I suprisingly do have one seed without a tracker. Tried the new update and i got 
```
INFO:transmission:Connecting to transmission daemon transmission at 192.168.68.131:9091
INFO:influxdb:Connecting to influxdb
ERROR:main:Error collecting data points from transmission client transmission
expected string or bytes-like object
INFO:main:Writing 0 data points to influxdb
```

**Comment by cheeseandcereal** [comment]
Whoops, yeah had a bug in my implementation. Updated again and this time tried actually testing with a torrent which I removed all trackers from. Seems to work for me. Pull latest update again and let me know if you're still having issues.

**Comment by KoalaV2** [comment]
Yep, all good now. Good work!
